services:
  mongo:
    image: mongo:5.0
    volumes:
      - dbdata:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    # uncomment the following line to pull the image from docker hub
    # image: index.docker.io/catarak/p5.js-web-editor:latest
    # uncomment the following lines if you don't want export all of the variables
    # defined in your .env file for testing
    env_file:
      - stack.env
    environment:
      - MONGO_URL=mongodb://mongo:27017/p5js-web-editor
      - API_URL=${API_URL}
      - GITHUB_ID=dummy
      - GITHUB_SECRET=dummy
      - CORS_ALLOW_LOCALHOST=${CORS_ALLOW_LOCALHOST}
      - ML5_LIBRARY_USERNAME=${ML5_LIBRARY_USERNAME}
      - ML5_LIBRARY_EMAIL=${ML5_LIBRARY_EMAIL}
      - ML5_LIBRARY_PASS=${ML5_LIBRARY_PASS}
      - PORT=${PORT}
      - PREVIEW_PORT=${PREVIEW_PORT}
      - EDITOR_URL=${EDITOR_URL}
      - PREVIEW_URL=${PREVIEW_URL}
      - EMAIL_ENABLED=${EMAIL_ENABLED}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - TRANSLATIONS_ENABLED=${TRANSLATIONS_ENABLED}
      - UI_ACCESS_TOKEN_ENABLED=${UI_ACCESS_TOKEN_ENABLED}
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}
      - SESSION_SECRET=dev_secret  # Not in stack.env, but required by express-session
    volumes:
      - .:/opt/node/app
      - /opt/node/app/node_modules
    ports:
      - '8010:8010'
      - '8002:8002'
    depends_on:
      - mongo
    command: ["npm", "run", "start:dev"]
volumes:
  dbdata:

